apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-static-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-static-app
  template:
    metadata:
      labels:
        app: sample-static-app
    spec:
      containers:
      - name: sample-static-app
        image: gcr.io/cicdproject-435004/sample-static-app:34
        ports:
        - containerPort: 80
