apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-static-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-static-app1
  template:
    metadata:
      labels:
        app: sample-static-app1
    spec:
      containers:
      - name: sample-static-app1
        image: gcr.io/cicdproject-435004/sample-static-app1:${{ github.run_number }}
        ports:
        - containerPort: 80
