name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
 
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
 
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
         
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
      
      - name: Authenticate Docker with GCR
        run: gcloud auth configure-docker
        
      - name: Build Docker Compose
        run: |
          docker-compose build

      - name: Push Docker Images
        run: |
          docker-compose push 
      
      - name: test
        run: |
          ls
          cat deployment.yaml
          cat service.yaml
          gcloud container clusters get-credentials cluster-sample --zone us-central1-c --project cicdproject-435004
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml --validate=false
          kubectl get services

